id = "cfengine"
name = "CFEngine"
version = "1.0.1"
schema_version = 1
authors = ["Ole Herman S. Elgesem <ole@cfengine.com>"]
description = "Syntax highlighting support for CFEngine policy language"
repository = "https://github.com/olehermanse/zed-cfengine"
languages = ["languages/cfengine"]

[grammars.cfengine]
repository = "https://github.com/olehermanse/tree-sitter-cfengine"
commit = "3651e94ad590f1d530a0a9d32862fa8816aba600"
